@echo off
SET RunCodeCoverage=%~1
SET NUNIT="C:\Program Files (x86)\NUnit 2.6.1\bin\nunit-console.exe"
SET ASSEMBLYFILTER="+[EDC.Common]* +[EDC.Interop]* +[EDC.ReadiNow.Common]* +[EDC.ReadiNow.Services]* +[EDC.SoftwarePlatform.Install.Common]* +[EDC.ReadiNow.Common.ConfigParser]* +[EDC.SoftwarePlatform.Services]* +[EDC.ReadiNow.Silverlight.Solution]* +[ReadiNow.Activities]* +[EDC.SoftwarePlatform.Migration]* +[ReadiNow.DocGen]* +[EDC.SoftwarePlatform.WebApi]* +[EDC.SoftwarePlatform.Web]*"
SET TARGETDIR=".\Tests"
SET NUNITARGS="/nologo /nodots /framework=net-4.5 /config=SmokeTest UnitTests.nunit"	
SET NUNITERRORLEVEL=0
if not exist %NUNIT% SET NUNIT="C:\Program Files (x86)\NUnit 2.6.3\bin\nunit-console.exe"
if exist %NUNIT% goto runtests
echo cannot find nunit
exit /b 1 

:runtests
xcopy /y /v /f "C:\Program Files\ReadiNow\SoftwarePlatform\Web\SpApi\bin\System.Net.Http.Formatting.dll" .\Tests\
xcopy /y /v /f "C:\Program Files\ReadiNow\SoftwarePlatform\Web\SpApi\bin\System.Web.Http.dll" .\Tests\

IF "%RunCodeCoverage%"=="" (	
	%NUNIT% /nologo /nodots /framework=net-4.5 /config=SmokeTest ".\Tests\UnitTests.nunit"
) ELSE (
	xcopy /y /v /f "C:\Program Files\ReadiNow\SoftwarePlatform\Bin\EDC.*" .\Tests\*.*
	xcopy /y /v /f "C:\Program Files\ReadiNow\SoftwarePlatform\Web\Platform\bin\EDC.*" .\Tests\*.*
	xcopy /y /v /f "C:\Program Files\ReadiNow\SoftwarePlatform\Web\SpApi\bin\EDC.*" .\Tests\*.*	

	.\OpenCover\OpenCover.Console.exe -returntargetcode -register:user -target:%NUNIT% -targetdir:%TARGETDIR% -targetargs:%NUNITARGS% -filter:%ASSEMBLYFILTER% -output:"Test_CoverageResults.xml" -excludebyfile:AutoGeneratedTypes.*.cs -mergebyhash	
		
	SET NUNITERRORLEVEL=%errorlevel%

	IF EXIST Tests\TestResult.xml xcopy /y /v /f Tests\TestResult.xml *.*

	IF EXIST CodeCovReport rd /q /s CodeCovReport
	mkdir CodeCovReport
	.\ReportGenerator\ReportGenerator.exe -reports:"Test_CoverageResults.xml" -targetdir:"CodeCovReport" -reporttypes:HtmlSummary

	exit /b %NUNITERRORLEVEL% 
)