// Copyright 2011-2016 Global Software Innovation Pty Ltd

namespace EDC.ReadiNow.CAST.Template.Model
{
	/// <summary>
    /// This class was auto-generated by a templating tool on July 20, 2016.
    /// </summary>
	public static class ManagedUserSchema
	{
		//
		// Managed User
		//
		public const string ManagedUserType = "cast:managedUser";
		
		//
		// Name
		//
		internal static string NameField
        {
            get { return "core:name"; }
        }
		
		//
		// Remote ID
		//
		internal static string RemoteIdField
        {
            get { return "cast:userRemoteId"; }
        }

		//
		// Managed Tenant - Users
		//
		internal static string ManagedTenantLookup
        {
            get { return "cast:userInTenant"; }
        }

		//
		// Managed User Status
		//
		internal static string ManagedUserStatusEnum
        {
            get { return "cast:userStatus"; }
        }

		//
		// Roles
		//
		internal static string RolesRelationship
        {
            get { return "cast:userRoles"; }
        }
	}
}