// Copyright 2011-2016 Global Software Innovation Pty Ltd

namespace EDC.ReadiNow.CAST.Template.Model
{
	/// <summary>
    /// This class was auto-generated by a templating tool against the
	/// CAST application file marked as published on '2016-12-07 00:40:35Z'.
    /// </summary>
	public static class ManagedRoleSchema
	{
		//
		// Managed Role
		//
		public const string ManagedRoleType = "cast:managedRole";
		
		//
		// Name
		//
		internal static string NameField
        {
            get { return "core:name"; }
        }
		
		//
		// Remote ID
		//
		internal static string RemoteIdField
        {
            get { return "cast:roleRemoteId"; }
        }

		//
		// Managed Tenant - Roles
		//
		internal static string ManagedTenantLookup
        {
            get { return "cast:roleInTenant"; }
        }

		//
		// Users - Roles
		//
		internal static string UsersRelationship
        {
            get { return "cast:roleAppliesToUsers"; }
        }
	}
}