// Copyright 2011-2016 Global Software Innovation Pty Ltd

namespace EDC.ReadiNow.CAST.Template.Model
{
	/// <summary>
    /// This class was auto-generated by a templating tool on July 20, 2016.
    /// </summary>
	public static class ManagedAppSchema
	{
		//
		// Managed App
		//
		public const string ManagedAppType = "cast:managedApp";
		
		//
		// Name
		//
		internal static string NameField
        {
            get { return "core:name"; }
        }
		
		//
		// App Id
		//
		internal static string AppIdField
        {
            get { return "cast:appIdField"; }
        }
		
		//
		// Publisher
		//
		internal static string PublisherField
        {
            get { return "cast:appPublisherField"; }
        }
		
		//
		// Publisher Url
		//
		internal static string PublisherUrlField
        {
            get { return "cast:appPublisherUrlField"; }
        }
		
		//
		// Release Date
		//
		internal static string ReleaseDateField
        {
            get { return "cast:appReleaseDate"; }
        }

		//
		// App Requires App
		//
		internal static string IsRequiredByAppRelationship
        {
            get { return "cast:appRequiresApps"; }
        }

		//
		// App Requires App Versions
		//
		internal static string RequiredAppVersionsRelationship
        {
            get { return "cast:appRequiresAppVersions"; }
        }

		//
		// App Version Requires App
		//
		internal static string IsRequiredByAppVersionRelationship
        {
            get { return "cast:appVersionRequiresApps"; }
        }

		//
		// Application Has Versions
		//
		internal static string VersionsRelationship
        {
            get { return "cast:applicationHasVersions"; }
        }

		//
		// Customer Can Access App
		//
		internal static string AccessibleByRelationship
        {
            get { return "cast:appAccessibleByCustomer"; }
        }

		//
		// Product Includes App
		//
		internal static string IncludedInProductRelationship
        {
            get { return "cast:productIncludesApp"; }
        }
	}
}