// Copyright 2011-2016 Global Software Innovation Pty Ltd

namespace EDC.ReadiNow.CAST.Template.Model
{
	/// <summary>
    /// This class was auto-generated by a templating tool on July 20, 2016.
    /// </summary>
	public static class PlatformDatabaseSchema
	{
		//
		// Platform Database
		//
		public const string PlatformDatabaseType = "cast:platformDatabase";
		
		//
		// Name
		//
		internal static string NameField
        {
            get { return "core:name"; }
        }
		
		//
		// Catalog
		//
		internal static string CatalogField
        {
            get { return "cast:platformDatabaseCatalog"; }
        }
		
		//
		// Last Contact
		//
		internal static string LastContactField
        {
            get { return "cast:platformDatabaseLastContact"; }
        }
		
		//
		// Server
		//
		internal static string ServerField
        {
            get { return "cast:platformDatabaseServer"; }
        }

		//
		// Managed Platform - Database History
		//
		internal static string ManagedPlatformLookup
        {
            get { return "cast:platformDatabaseHistory"; }
        }
	}
}