// Copyright 2011-2016 Global Software Innovation Pty Ltd

namespace EDC.ReadiNow.CAST.Template.Model
{
	/// <summary>
    /// This class was auto-generated by a templating tool against the
	/// CAST application file marked as published on '2016-11-02 06:20:34Z'.
    /// </summary>
	public static class VerificationLinkSchema
	{
		//
		// Verification Link
		//
		public const string VerificationLinkType = "cast:verificationLink";
		
		//
		// Name
		//
		internal static string NameField
        {
            get { return "core:name"; }
        }
		
		//
		// Mailed To
		//
		internal static string MailedToField
        {
            get { return "cast:verificationLinkMailedTo"; }
        }
		
		//
		// URI
		//
		internal static string UriField
        {
            get { return "cast:verificationLinkURI"; }
        }

		//
		// Verification Link - Managed Customer
		//
		internal static string ManagedCustomerLookup
        {
            get { return "cast:verificationLinkCustomer"; }
        }
	}
}