//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDC.ReadiNow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDC.ReadiNow.Resources.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos; value to yes/no data type..
        /// </summary>
        public static string CastingBoolMessageTextFormat {
            get {
                return ResourceManager.GetString("CastingBoolMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos; value to currency data type..
        /// </summary>
        public static string CastingCurrencyMessageTextFormat {
            get {
                return ResourceManager.GetString("CastingCurrencyMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos; value to date data type..
        /// </summary>
        public static string CastingDateMessageTextFormat {
            get {
                return ResourceManager.GetString("CastingDateMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos; value to date-time data type..
        /// </summary>
        public static string CastingDateTimeMessageTextFormat {
            get {
                return ResourceManager.GetString("CastingDateTimeMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos; value to decimal data type..
        /// </summary>
        public static string CastingDecimalMessageTextFormat {
            get {
                return ResourceManager.GetString("CastingDecimalMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos; value to integer data type..
        /// </summary>
        public static string CastingIntegerMessageTextFormat {
            get {
                return ResourceManager.GetString("CastingIntegerMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos; value to Time data type..
        /// </summary>
        public static string CastingTimeMessageTextFormat {
            get {
                return ResourceManager.GetString("CastingTimeMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDC.
        /// </summary>
        public static string CompanyPath {
            get {
                return ResourceManager.GetString("CompanyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}..
        /// </summary>
        public static string DateTimeRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("DateTimeRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is outside of the allowable range..
        /// </summary>
        public static string DefaultDateTimeRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("DefaultDateTimeRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Platform Calendar Event.
        /// </summary>
        public static string DefaultICalSummary {
            get {
                return ResourceManager.GetString("DefaultICalSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is outside of the allowable range..
        /// </summary>
        public static string DefaultNumericRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("DefaultNumericRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are problems with this file and it cannot be imported..
        /// </summary>
        public static string FileFormatError {
            get {
                return ResourceManager.GetString("FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralPath {
            get {
                return ResourceManager.GetString("GeneralPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row number {0} \t could not be imported. There is more than 1  &apos;{1}&apos; named &apos;{2}&apos;
        ///{3}.
        /// </summary>
        public static string ImportFailedRelMultiRelatedInstancesTextFormat {
            get {
                return ResourceManager.GetString("ImportFailedRelMultiRelatedInstancesTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row number {0} \t could not be imported. Couldn&apos;t find &apos;{1}&apos; named &apos;{2}&apos;
        ///{3}.
        /// </summary>
        public static string ImportFailedRelTextFormat {
            get {
                return ResourceManager.GetString("ImportFailedRelTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row number {0} \t could not be imported. {1}
        ///{2}.
        /// </summary>
        public static string ImportFailedTextFormat {
            get {
                return ResourceManager.GetString("ImportFailedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the import operation. Exception : {0}.
        /// </summary>
        public static string ImportFileError {
            get {
                return ResourceManager.GetString("ImportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while importing CSV row (Exception: {0}.
        /// </summary>
        public static string ImportingCsvRowError {
            get {
                return ResourceManager.GetString("ImportingCsvRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while importing data from Excel (Exception: {0}.
        /// </summary>
        public static string ImportingExcelDataError {
            get {
                return ResourceManager.GetString("ImportingExcelDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while importing Excel row (Exception: {0}.
        /// </summary>
        public static string ImportingExcelRowError {
            get {
                return ResourceManager.GetString("ImportingExcelRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} records successfully imported..
        /// </summary>
        public static string ImportSuccessfulTextFormat {
            get {
                return ResourceManager.GetString("ImportSuccessfulTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the import task..
        /// </summary>
        public static string ImportTaskDeleteError {
            get {
                return ResourceManager.GetString("ImportTaskDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row number {0} \t is imported successfully. Warning! : {1}
        ///{2}.
        /// </summary>
        public static string ImportWarningTextFormat {
            get {
                return ResourceManager.GetString("ImportWarningTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalError.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Platform Calendar Update.
        /// </summary>
        public static string InvalidCalendarEmailSubject {
            get {
                return ResourceManager.GetString("InvalidCalendarEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is required..
        /// </summary>
        public static string MandatoryMessageTextFormat {
            get {
                return ResourceManager.GetString("MandatoryMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be before {0}..
        /// </summary>
        public static string MaximumDateTimeRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("MaximumDateTimeRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; length must not be greater than {1}.
        /// </summary>
        public static string MaximumLengthMessageTextFormat {
            get {
                return ResourceManager.GetString("MaximumLengthMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} value truncated to maximum length {1}..
        /// </summary>
        public static string MaximumLengthWarningTextFormat {
            get {
                return ResourceManager.GetString("MaximumLengthWarningTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be less than {0}..
        /// </summary>
        public static string MaximumNumericRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("MaximumNumericRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input &apos;{0}&apos; does not specify a valid time value..
        /// </summary>
        public static string MaximumTimeRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("MaximumTimeRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; value must not be greater than {1}.
        /// </summary>
        public static string MaximumValueMessageTextFormat {
            get {
                return ResourceManager.GetString("MaximumValueMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Invitation.
        /// </summary>
        public static string MeetingInvitation {
            get {
                return ResourceManager.GetString("MeetingInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be after {0}..
        /// </summary>
        public static string MinimumDateTimeRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("MinimumDateTimeRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; length must not be less than {1}.
        /// </summary>
        public static string MinimumLengthMessageTextFormat {
            get {
                return ResourceManager.GetString("MinimumLengthMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than {0}..
        /// </summary>
        public static string MinimumNumericRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("MinimumNumericRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; value must not be less than {1}.
        /// </summary>
        public static string MinimumValueMessageTextFormat {
            get {
                return ResourceManager.GetString("MinimumValueMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decimal &apos;{0}&apos; has been truncated to &apos;{1}&apos;..
        /// </summary>
        public static string NumberTruncated {
            get {
                return ResourceManager.GetString("NumberTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}..
        /// </summary>
        public static string NumericRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("NumericRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be included within the following set &apos;{0}&apos;..
        /// </summary>
        public static string NumericSetRangeConstraintHelpMessage {
            get {
                return ResourceManager.GetString("NumericSetRangeConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required..
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too short; the minimum length is {0} characters..
        /// </summary>
        public static string PasswordIsTooShort {
            get {
                return ResourceManager.GetString("PasswordIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one digit character..
        /// </summary>
        public static string PasswordMustHaveDigit {
            get {
                return ResourceManager.GetString("PasswordMustHaveDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one lowercase character..
        /// </summary>
        public static string PasswordMustHaveLowercase {
            get {
                return ResourceManager.GetString("PasswordMustHaveLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one non-alphanumeric character..
        /// </summary>
        public static string PasswordMustHaveSpecial {
            get {
                return ResourceManager.GetString("PasswordMustHaveSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one uppercase character..
        /// </summary>
        public static string PasswordMustHaveUppercase {
            get {
                return ResourceManager.GetString("PasswordMustHaveUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text must match the &apos;{0}&apos; pattern.
        /// </summary>
        public static string PatternMatchMessageTextFormat {
            get {
                return ResourceManager.GetString("PatternMatchMessageTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadiNow.
        /// </summary>
        public static string ProductPath {
            get {
                return ResourceManager.GetString("ProductPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex pattern was not set..
        /// </summary>
        public static string RegexNullExceptionMessage {
            get {
                return ResourceManager.GetString("RegexNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerPath {
            get {
                return ResourceManager.GetString("ServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Platform Calendar Invite.
        /// </summary>
        public static string SoftwarePlatformCalendarInvite {
            get {
                return ResourceManager.GetString("SoftwarePlatformCalendarInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must be between {0} and {1} characters in length..
        /// </summary>
        public static string StringLengthConstraintHelpMessage {
            get {
                return ResourceManager.GetString("StringLengthConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text value is not valid..
        /// </summary>
        public static string StringRegexConstraintHelpMessage {
            get {
                return ResourceManager.GetString("StringRegexConstraintHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doesn&apos;t support multiple types..
        /// </summary>
        public static string TypeDoesnotSupportMultiTypesError {
            get {
                return ResourceManager.GetString("TypeDoesnotSupportMultiTypesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is Abstract..
        /// </summary>
        public static string TypeIsAbstractError {
            get {
                return ResourceManager.GetString("TypeIsAbstractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected occurred during the current operation..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Platform Calendar Update - {0}.
        /// </summary>
        public static string ValidCalendarEmailSubject {
            get {
                return ResourceManager.GetString("ValidCalendarEmailSubject", resourceCulture);
            }
        }
    }
}
