// Copyright 2011-2016 Global Software Innovation Pty Ltd

(function () {
    "use strict";

    /**
    * Module implementing the security query view.
    *
    * @module securityQuery
    */
    angular.module('app.securityQuery', ['app.security.directives.spSecurityAccessControl', 'sp.navService', 'mod.common.alerts', 'mod.app.accessControl.service'])
        .config(function ($stateProvider) {
            $stateProvider.state('securityQueries', {
                url: '/{tenant}/{eid}/securityQueries?path',
                templateUrl: 'security/securityQuery.tpl.html'
            });
        })
        .controller('securityQueryController', function ($scope, spNavService, spAlertsService, spAccessControlService, $state) {

            function raiseActionEvent(action) {
                $scope.$broadcast('accessAction', { action: action });
            }

            // Remove any alerts that were generated by this page.
            function clearPageAlerts() {
                spAlertsService.removeAlertsWhere({ page: $state.current });
            }

            // The model
            $scope.model = {
                accessOptions: {
                    mode: spAccessControlService.viewMode === spAccessControlService.modes.view ? 'view' : 'edit',
                    containerLoaded: true
                },
                toolbar: {}
            };

            // Cancel any changes
            $scope.onCancelClick = function () {
                spNavService.navigateInternal().then(function () {
                    clearPageAlerts();
                    raiseActionEvent('cancel');
                });
            };

            // Save any changes
            $scope.onSaveClick = function () {
                raiseActionEvent('save');
            };

            // Switch to edit mode
            $scope.onEditClick = function () {
                raiseActionEvent('edit');
            };

            var viewModeToolbarButtons = [
                {
                    text: "Edit",
                    icon: "assets/images/toolbar_edit.png",
                    click: $scope.onEditClick
                }
            ];

            var editModeToolbarButtons = [
                {
                    text: "Save",
                    icon: "assets/images/toolbar_save.png",
                    click: $scope.onSaveClick
                },
                {
                    text: "Cancel",
                    icon: "assets/images/toolbar_close.png",
                    click: $scope.onCancelClick
                }
            ];

            // Update the toolbar buttons when the mode changes
            $scope.$watch('model.accessOptions.mode', function () {
                $scope.model.toolbar.buttons = $scope.model.accessOptions.mode === 'view' ? viewModeToolbarButtons : editModeToolbarButtons;
            });
        });
})();